/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_kunrui_kunrui_serverStart */
#include "tcpServer.h"
#include "tcpFunction.h"
#include "Blowfish.h"
#include "imsi2phone.h"
#include "sqlite3.h"

#define LOG_TAG "System.out"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOG_TAG, __VA_ARGS__)

#ifndef _Included_com_example_kunrui_kunrui_serverStart
#define _Included_com_example_kunrui_kunrui_serverStart
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_kunrui_kunrui_serverStart
 * Method:    serverStart
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_kunrui_kunrui_serverStart_serverStart
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
